language: cpp

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "pR9q4lFrg3nvtDEArMdtfegVCWO1Ed6o0vcgnJQaJ91Z/oO3dUq/zkhyEBxTz74e44CTDuhGvFiSq1ZCcrXVLc+/X0xrrqaTyZUScfJYCysGPxbZ+tEE3+wh9WlwZj3befBKft+cUodoAkzVIY7mLgoIh04GnaU8Fotjhse0zF24rg+YnZVrqnvv5st/k9bZBCg+kM7YLGKMcdMQNKD+8UQKYU2lm7n+qeyLdv3ZPZeq3vZmYxpc/9NkvyqznsILQML8E7DSm3bOOdpR4hTkWZWpeOoDPV6D4XK3G+u1xocgqdecippskIvKbItHwQUqdzFjlX1c6Nv5hMYLVMoK3gQxF5V5C08Ajgz4q5i6a0HAuQ5a51/8qoU5qWYnKL/0EqiOGzBRnCowpzSjN1hDdg3rS0Tmy5nfSafem9PRdTC/I1gylmv6rMOSsTlkjdxF4Pk859tGodrlqZ5Nly9xyFt3qfaG9sUXtFB8DX0Lhh//68iZrhRS+gEl5cAzyJO/qZgjQ5hiEF/jjAPqwzsA09xvUXRNlU00ciX3Vo1UwySPd6mgppPbJpFDk86wd9y/ETxuNFMAVAz/HAzyS3og3FJiyPuc3ZmGE6T2TvjTC35fxUhCl46I0JF4vv+3O76KOhBUBcl1VQWqD+KXCN/u2W+zfCyNT/KXixhVh4Gdj0Q="

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt
  
addons:
  coverity_scan:
    project:
      name: Shymaxtic/CANIFModule
      description: Posix CAN interface
    notification_email: shymaxtic@gmail.com
    build_command_prepend: make clean
    build_command: make
    branch_pattern: master

script: 
  - make
